---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-spot-rescheduler
  namespace: kube-system
  labels:
    app: k8s-spot-rescheduler
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-spot-rescheduler
  template:
    metadata:
      labels:
        app: k8s-spot-rescheduler
    spec:
      containers:
        - image: k8s-spot-rescheduler
          name: k8s-spot-rescheduler
          resources:
            limits:
              cpu: 20m
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 50Mi
          command:
            - /rescheduler
            - -v=2
            - --running-in-cluster=true
            - --namespace=kube-system
            - --housekeeping-interval=10s
            - --node-drain-delay=10m
            - --pod-eviction-timeout=2m
            - --max-graceful-termination=2m
            - --listen-address=0.0.0.0:9235
            - --on-demand-node-label=node-role.kubernetes.io/worker
            - --spot-node-label=node-role.kubernetes.io/spot-worker
